server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**

        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/